# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "229e991b487b51bbb3a920cd59108fc986b019a15ba64165b8496abe494e46c4"  # change this!
  limiter: false  # enable this when running the instance for a public usage on the internet
  image_proxy: true
search: 
  formats:
    - html
    - json
engines:
  yahoo:
    enabled: true
    weight: 2
    params:
      p: '{query}'
  duckduckgo:
    enabled: true
    weight: 1
    params:
      kl: 'jp-ja'

redis:
  url: redis://redis:6379/0
