use_default_settings: false

server:
  secret_key: "f334ee5706379414b285254161f38e742b879e25e692b98bfeeb243a22af4027"   
  base_url: "https://searxng.lacchinh.com"
  limiter: false
  image_proxy: true
  formats:
    - html
    - json

redis:
  url: redis://redis:6379/0
